apiVersion: v1
kind: PersistentVolume
metadata:
  name: quickstart-es-default-0
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/elasticsearch/data0"
---
