apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaegar
spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
  storage:
    type: cassandra
    options:
      es:
        server-urls: http://cassandra:9042
