apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: simple-prod
  namespace: oai
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  strategy: production
  collector:
    maxReplicas: 5
    resources:
      limits:
        cpu: 3000m
        memory: 8Gi
