apiVersion: v1
kind: Pod
metadata:
  name: httpproxy
  labels:
    app: httpproxy
spec:
  initContainers:
  - name: init-networking
    image: tolgaomeratalay/init-networking
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
      privileged: true
  containers:
  - name: service
    image: tolgaomeratalay/dummyhttp:latest
    ports:
    - containerPort: 80
  - name: proxy
    image: tolgaomeratalay/reverseproxy:latest
    ports:
    - containerPort: 11095
