apiVersion: v1
kind: PersistentVolume
metadata:
  name: jaegar-cassandra #cassandra-data
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/usr/cassandra/data"
