apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-0
  labels:
    app: elasticsearch-master
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/elasticsearch/data0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-1
  labels:
    app: elasticsearch-master
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/elasticsearch/data1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-master-2
  labels:
    app: elasticsearch-master
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "elasticsearch/data2"
